// Public questions available on the AIF-C01 ExamTopics page (page 1).
const AWS_AIF_C01_DATA = [{
  "examNumber": "AIF-C01",
  "title": "AWS Certified AI Practitioner (AIF-C01)",
  "totalQuestions": 10,
  "source": "https://www.examtopics.com/exams/amazon/aws-certified-ai-practitioner-aif-c01/view/",
  "questions": [
    {"number":1,"question":"A company makes forecasts each quarter to decide how to optimize operations to meet expected demand. The company uses ML models to make these forecasts. An AI practitioner is writing a report about the trained ML models to provide transparency and explainability to company stakeholders. What should the AI practitioner include in the report to meet the transparency and explainability requirements?","options":{"A":"Code for model training","B":"Partial dependence plots (PDPs)","C":"Sample data for training","D":"Model convergence tables"},"correct":["B"],"multiple":false},
    {"number":2,"question":"A law firm wants to build an AI application by using large language models (LLMs). The application will read legal documents and extract key points from the documents. Which solution meets these requirements?","options":{"A":"Build an automatic named entity recognition system.","B":"Create a recommendation engine.","C":"Develop a summarization chatbot.","D":"Develop a multi-language translation system."},"correct":["C"],"multiple":false},
    {"number":3,"question":"A company wants to classify human genes into 20 categories based on gene characteristics. The company needs an ML algorithm to document how the inner mechanism of the model affects the output. Which ML algorithm meets these requirements?","options":{"A":"Decision trees","B":"Linear regression","C":"Logistic regression","D":"Neural networks"},"correct":["A"],"multiple":false},
    {"number":4,"question":"A company has built an image classification model to predict plant diseases from photos of plant leaves. The company wants to evaluate how many images the model classified correctly. Which evaluation metric should the company use to measure the model's performance?","options":{"A":"R-squared score","B":"Accuracy","C":"Root mean squared error (RMSE)","D":"Learning rate"},"correct":["B"],"multiple":false},
    {"number":5,"question":"A company is using a pre-trained large language model (LLM) to build a chatbot for product recommendations. The company needs the LLM outputs to be short and written in a specific language. Which solution will align the LLM response quality with the company's expectations?","options":{"A":"Adjust the prompt.","B":"Choose an LLM of a different size.","C":"Increase the temperature.","D":"Increase the Top K value."},"correct":["A"],"multiple":false},
    {"number":6,"question":"A company uses Amazon SageMaker for its ML pipeline in a production environment. The company has large input data sizes up to 1 GB and processing times up to 1 hour. The company needs near real-time latency. Which SageMaker inference option meets these requirements?","options":{"A":"Real-time inference","B":"Serverless inference","C":"Asynchronous inference","D":"Batch transform"},"correct":["C"],"multiple":false},
    {"number":7,"question":"A company is using domain-specific models. The company wants to avoid creating new models from the beginning. The company instead wants to adapt pre-trained models to create models for new, related tasks. Which ML strategy meets these requirements?","options":{"A":"Increase the number of epochs.","B":"Use transfer learning.","C":"Decrease the number of epochs.","D":"Use unsupervised learning."},"correct":["B"],"multiple":false},
    {"number":8,"question":"A company is building a solution to generate images for protective eyewear. The solution must have high accuracy and must minimize the risk of incorrect annotations. Which solution will meet these requirements?","options":{"A":"Human-in-the-loop validation by using Amazon SageMaker Ground Truth Plus","B":"Data augmentation by using an Amazon Bedrock knowledge base","C":"Image recognition by using Amazon Rekognition","D":"Data summarization by using Amazon QuickSight Q"},"correct":["A"],"multiple":false},
    {"number":9,"question":"A company wants to create a chatbot by using a foundation model (FM) on Amazon Bedrock. The FM needs to access encrypted data that is stored in an Amazon S3 bucket. The data is encrypted with Amazon S3 managed keys (SSE-S3). The FM encounters a failure when attempting to access the S3 bucket data. Which solution will meet these requirements?","options":{"A":"Ensure that the role that Amazon Bedrock assumes has permission to decrypt data with the correct encryption key.","B":"Set the access permissions for the S3 buckets to allow public access to enable access over the internet.","C":"Use prompt engineering techniques to tell the model to look for information in Amazon S3.","D":"Ensure that the S3 data does not contain sensitive information."},"correct":["A"],"multiple":false},
    {"number":10,"question":"A company wants to use language models to create an application for inference on edge devices. The inference must have the lowest latency possible. Which solution will meet these requirements?","options":{"A":"Deploy optimized small language models (SLMs) on edge devices.","B":"Deploy optimized large language models (LLMs) on edge devices.","C":"Incorporate a centralized small language model (SLM) API for asynchronous communication with edge devices.","D":"Incorporate a centralized large language model (LLM) API for asynchronous communication with edge devices."},"correct":["A"],"multiple":false}
  ]
}];
